name: Run Jupy Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t jupy -f Dockerfile .
        
      - name: Run Docker container
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: docker run --rm --name jupy jupy
